### ISSUE TITLE
Missing manifest file

### ISSUE THREAD

**Issue by codiebeulaine** [praekeltfoundation/contentrepo#285]
Unable to pull image as missing manifest file

**Comment by rudigiesler** [comment]
Hi, thanks for the issue.

I'm unable to reproduce it on my side, and researching this error message, it seems to be related to trying to pull an image tag that doesn't exist.

Which image tag are you trying to pull?

**Comment by codiebeulaine** [comment]
Hi Rudi,

Are you sure the image is public? Also getting error messages that say
denied

**Comment by rudigiesler** [comment]
Yes, the image is public, no auth required, on both docker hub and GHCR

On my local machine, running docker 25.0.4, the following all work fine:
```
sudo docker pull praekeltfoundation/contentrepo
sudo docker pull ghcr.io/praekeltfoundation/contentrepo
sudo docker pull praekeltfoundation/contentrepo:1.1.0
sudo docker pull ghcr.io/praekeltfoundation/contentrepo:1.1.0
```
